[book]
authors = ["Dylan Storey"]
language = "en"
multilingual = false
src = "src"
title = "GraphQLite Documentation"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/colliery-io/graphqlite"
edit-url-template = "https://github.com/colliery-io/graphqlite/edit/main/docs/{path}"
additional-css = []
additional-js = []

[output.html.fold]
enable = true
level = 1
